# Generated by Django 3.1.4 on 2021-01-06 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrustType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crust_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SauceAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sauce_amount', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='SauceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sauce_type', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crust_selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.crusttype')),
                ('sauce_amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.sauceamount')),
                ('sauce_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.saucetype')),
                ('size_selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.pizzasize')),
                ('topping_selection', models.ManyToManyField(to='pizza.Topping')),
            ],
        ),
    ]
