# Generated by Django 3.1.4 on 2021-01-06 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topping',
            name='topping',
            field=models.CharField(default='Cheese', max_length=50),
        ),
    ]
